sonar.organization=mzworthington
sonar.projectKey=mzworthington_steerco
sonar.exclusions=.github/workflows/**
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info,app/packages/core/coverage/lcov.info
